import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="pt-BR" className='overflow-x-hidden'>
      <body className={`${inter.className} box-border`}>
        <div className="bg-custom-lds w-[100vw] flex flex-col  ">
          {children}
          <Toaster/>
        </div>
      </body>
    </html>
  )
}
  